version: "3"

tasks:
  bootstrap:
    cmds:
      - mise install
      - pnpm install
      - pnpm codegen

  dev:
    cmds:
      - pnpm dev

  build:
    cmds:
      - pnpm build

  lint:
    cmds:
      - pnpm lint

  typecheck:
    cmds:
      - pnpm typecheck

  test:
    cmds:
      - pnpm test

  test:e2e:
    cmds:
      - pnpm test:e2e

  format:
    cmds:
      - pnpm format

  codegen:
    cmds:
      - pnpm codegen

  db:start:
    cmds:
      - pnpm db:start

  db:reset:
    cmds:
      - pnpm db:reset

  db:types:
    cmds:
      - pnpm db:types
